output_dir: "./new-results"
mode: "test"
batchsize: 48
search: True
add_kl: False
schedule_type: "constant"
warmup: 0.2
lr: 9e-3
max_steps: 100
weight_decay: 0.02
do_eval: True
eval_log_strategy: "steps"
eval_log_step: 1
peft_type: "llama-adapter"
adapter_len: 20
target_layers: 32
adapter_layers: 32