output_dir: "./new-results"
mode: "train"
batchsize: 1
search: True
add_kl: False
schedule_type: "constant"
warmup: 0.2
lr: 3e-2
max_steps: 100
weight_decay: 0.02
do_eval: True
eval_log_strategy: "steps"
eval_log_step: 1
peft_type: "prompt-tuning"
prompt_len: 10
target_layers: 32