output_dir: "./results"
model_name_or_path: "meta-llama/Llama-2-7b-chat-hf"
data_path: "/home/cmin/LLM-Interpretation-Playground/benchmarks/malicious_instruct/Jailbreak_LLM-main/data/MaliciousInstruct.txt"
mode: "train"
batchsize: 1
accumulation_steps: 16
search: True
add_kl: False
schedule_type: "constant"
warmup: 0.1
lr: 3e-4
eval_step: 5
epoch: 100
peft_type: "llama-adapter"
adapter_len: 20
adapter_layers: 32
training_set_name: happy_search_100
eval_set_name: happy_search_10_eval_heldout
attribute: "happy"
run_name: "emotion-100-3e-4-16bz"
push_name: "LlamaAdapter-emotion-100-3e-4-16bz"