output_dir: "./results"
model_name_or_path: "meta-llama/Llama-2-7b-chat-hf"
data_path: "/home/cmin/LLM-Interpretation-Playground/benchmarks/malicious_instruct/Jailbreak_LLM-main/data/MaliciousInstruct.txt"
mode: "train"
batchsize: 1
accumulation_steps: 32
search: True
add_kl: False
schedule_type: "constant"
warmup: 0.2
lr: 3e-4
epoch: 50
do_eval: True
peft_type: "llama-adapter"
adapter_len: 20
adapter_layers: 32
training_set_name: happy_search_100_greedy
eval_set_name: happy_search_10_eval_heldout
attribute: "happy"
run_name: "emotion-200-3e-4-greedy-50epoch-02warmup"
push_name: "LlamaAdapter-emotion-200-3e-4-greedy-50epoch-02warmup"