training_set_name: happy_search_1000_temp_fixed
eval_set_name: happy_search_10_eval_heldout
accumulation_steps: 1000
attribute: "happy"
run_name: "happy-1000-temp-fixed"
push_name: "LlamaAdapter-llama2-happy-1000-temp-fixed"