training_set_name: happy_search_1000_new
eval_set_name: happy_search_10_eval_heldout
accumulation_steps: 
attribute: "happy"
run_name: "happy-1000-temp-new"
push_name: "LlamaAdapter-llama2-happy-1000-temp-new"